services:
  - type: web
    name: jobsprint
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:///app/data/jobsprint.db
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ALIYUN_API_KEY
        value: "sk-ws-H.EMHXYIM.Plkd.MEQCIAGP5K7s5JveJ-t1k28Xzt4mt7NYu1c-n9ghwvdgxfsOAiBWdf_7ZH3cOru_M5qWx2iz1G8reuZb753HVBefHW744Q"
      - key: RESET_SECRET
        generateValue: true